### PR TITLE
handle discharge current as negative current value

### PR DESCRIPTION
**Pull request by buborh**
Discharge current is bad, this patch fix that issue.
The negative current is  ("serial current result" - 65535) *10 mA 
Feel free to change my code.

### CODE REVIEW

**Comment by rahmaevao** [comment]
Thank you for sharing your best practices.

My friend Uwe has already written to me by mail about this problem. But he doesn't know how to do pull requests. It's great that you brought up this issue.

In my opinion, for the purity of the code, you should not use magic numbers (655350, 327675). It is worth specifying the conversion explicitly.
Better to rename the `two_ints_into16` method to `convertTwoIntsToUint16`.
And create a `convertTwoIntsToInt16` method, with the following content:

```cpp
int16_t convertTwoIntsToInt16(int highbyte, int lowbyte) {
    int16_t value = convertTwoIntsToUint16(highbyte, lowbyte);
    if (value & 0b1000000000000000)  // Test for positive / negative with bit mask
    {
        value = ~ value;
        value = value * -1;
    }
    return value;
}
```

However, if you do not have the opportunity to do this and check, then I will upload your changes right away. I myself cannot verify this, since I no longer have this BMS at hand.

**Review by rahmaevao — COMMENTED** [review]
Thank you for sharing your best practices.

My friend Uwe has already written to me by mail about this problem. But he doesn't know how to do pull requests. It's great that you brought up this issue.

In my opinion, for the purity of the code, you should not use magic numbers (655350, 327675). It is worth specifying the conversion explicitly.
Better to rename the `two_ints_into16` method to `convertTwoIntsToUint16`.
And create a `convertTwoIntsToInt16` method, with the following content:

```cpp
int16_t convertTwoIntsToInt16(int highbyte, int lowbyte) {
    int16_t value = convertTwoIntsToUint16(highbyte, lowbyte);
    if (value & 0b1000000000000000)  // Test for positive / negative with bit mask
    {
        value = ~ value;
        value = value * -1;
    }
    return value;
}
```

However, if you do not have the opportunity to do this and check, then I will upload your changes right away. I myself cannot verify this, since I no longer have this BMS at hand.

**Review by rahmaevao — COMMENTED** [review]
It works? Have you tested positive or negative current?

Are other fields readable?

If so, be sure to drain. After all, you're a cool dude!

**Comment by buborh** [comment]
I've tested. Work with negativ and positive values too, and all other value can be readed.

**Comment by rahmaevao** [comment]
@buborh  you're cool. Thanks for your input.

**Pull request merged**
